[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "DicomPixelAnon"
version = "1.0.0"
license={text="Apache-2.0"}
readme="README.md"
description="DICOM Pixel Anonymisation"
